In [1]:
import numpy as np

In [3]:
cvalue = [25.6, 24.8, 36.8, 26.9, 35.7, 11.9]
print(type(cvalue))

<class 'list'>


In [4]:
c = np.array(cvalue)
print(c)
print(type(c))

[25.6 24.8 36.8 26.9 35.7 11.9]
<class 'numpy.ndarray'>


In [5]:
#General Conversion for celcius to Faran
fvalues =[]
for x in cvalue:
    fvalues.append(x*9/5 + 32)      #Formula toconvert cel to Faran   *9/5 +32
print(fvalues)
print(type(fvalues))

[78.08, 76.64, 98.24, 80.42, 96.26, 53.42]
<class 'list'>


In [5]:
#numpy simple calculation
print(c * 9/5 + 32)

[78.08 76.64 98.24 80.42 96.26 53.42]


In [45]:
#Examples
import numpy as np
a = np.array([1,2,3])
print (a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [9]:
#more than one dimension
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [13]:
#minimum dimension
a = np.array([1,2,3,4,5], ndmin = 2)
print(a)

[[1 2 3 4 5]]


In [11]:
#dtype parameter
a = np.array([1,2,3], dtype = complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


# dtype

In [14]:
import numpy as np

In [15]:
dt = np.dtype(np.int32)
print(dt)

int32


In [16]:
#int8, int16, int32, int64 can be replaced by equivalent strinf 'i1', 'i2', 'i4', etc.
dt = np.dtype('i4')
print(dt)

int32


In [17]:
#using endian notation
dt = np.dtype('>i4')
print(dt)

>i4


In [18]:
#first create structured data type
dt = np.dtype([('age', np.int8)])
print(dt)

[('age', 'i1')]


In [19]:
#now apply it to ndarray object
a = np.array([(10,),(20,),(30,)], dtype = dt)
print(a)

[(10,) (20,) (30,)]


In [20]:
#array name can be usedto access content of age column
print(a['age'])

[10 20 30]


In [21]:
#Example
x1 = (10)
x2 = (10,)
print(x1, type(x1))
print(x2, type(x2))


10 <class 'int'>
(10,) <class 'tuple'>


In [23]:
##Example
student = np.dtype([('name', 'S20'), ('age', 'i1'), ('marks', 'f4')])
print(student)

a = np.array([('abc', 21, 50), ('xyz', 18, 75)], dtype = student)
print(a)

print(a['age'])
print(a['name'] [1])

[('name', 'S20'), ('age', 'i1'), ('marks', '<f4')]
[(b'abc', 21, 50.) (b'xyz', 18, 75.)]
[21 18]
b'xyz'


# Attributes of nd Array

In [24]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [25]:
#this resize the ndarray
a.shape = (3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [26]:
a = np.array([[1,2,3],[4,5,6]])
b = a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [30]:
#an array of equally spaced number
a =np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [32]:
#Above is one dimension array
print(a.ndim)

1


In [31]:
#now reshape it
b =a.reshape(2,4,3)
print(b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [33]:
#b is having 3 dimension
print(b.ndim)

3


In [34]:
#dtype of array is int8(1 byte)
x = np.array([1,2,3,4,5], dtype = np.int8)
print(x.itemsize)

1


In [36]:
#dtype of array is now float32 (4 bytes)
x = np.array([1,2,3,4,5], dtype = np.float32)
print(x.itemsize)

4


In [40]:
#Example
student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')])
                    
a = np.array([('abc', 21, 50),('xyz', 21, 75)], dtype = student)
print(a.itemsize)

25


In [41]:
x = np.array([1,2,3,4,5])
print(x.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False


In [42]:
print(x.flags['WRITEABLE'])

True


In [43]:
x[3] = 10
print(x)

[ 1  2  3 10  5]


In [44]:
x.flags['WRITEABLE'] = False
x[1] = 11
print(x)

ValueError: assignment destination is read-only

# Method of creating NumPy array

In [1]:
import numpy as np
x = np.empty([3,2], dtype = int)
print(x)

[[0 0]
 [0 0]
 [0 0]]


In [2]:
#array of 5 zeros. Default dtype is Float
x = np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


In [3]:
x = np.zeros(5, dtype = int)
print(x)

[0 0 0 0 0]


In [4]:
#custom type
x = np.zeros((2,2), dtype = [('x', 'i4'), ('y', 'i4')])
print(x)

[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


In [5]:
#array of five ones. Default dtype id float
x = np.ones(5)
print(x)


[1. 1. 1. 1. 1.]


In [6]:
x = np.ones(5, dtype = int)
print(x)

[1 1 1 1 1]


In [7]:
x = np.ones([2,2], dtype = int)
print(x)

[[1 1]
 [1 1]]


##Array from Existing Data

In [8]:
#Convert list to ndarray
import numpy as np

x = [1,2,3]
a = np.asarray(x)
print(a)

[1 2 3]


In [10]:
#dtype is set
a = np.asarray(x, dtype = float)
print(a)

[1. 2. 3.]


In [12]:
#ndarray from Tuples
x = (1,2,3)
a = np.asarray(x)
print(a)

[1 2 3]


In [13]:
#ndarray from list of Tuples
x = [(1,2,3), (4,5)]
a = np.asarray(x)
print(a)

[(1, 2, 3) (4, 5)]


In [18]:
#Example
import numpy as np
s = b'Hello World'           #'b' is mendetory as its saved in byte
a = np.frombuffer(s, count = 3, offset = 4, dtype = 'S1')
print(a)

[b'o' b' ' b'W']


In [22]:
d = b'Hay World'
a = np.frombuffer(d, count = 2, offset = 2, dtype = 'S2')
print(a)

[b'y ' b'Wo']


In [23]:
#Array From Numerical Range
#Range

import numpy as np

x = np.arange(5)
print(x)

[0 1 2 3 4]


In [24]:
#dtype set
x = np.arange(5, dtype = float)
print(x)

[0. 1. 2. 3. 4.]


In [25]:
#Start and Stop Parameter Set
x = np.arange(10,20,2)     #2 is step
print(x)

[10 12 14 16 18]


In [29]:
#Linespace
import numpy as np
x = np.linspace(10,20,5)
print(x)

[10.  12.5 15.  17.5 20. ]


In [31]:
#endpoint set to false
x = np.linspace(10,20,5, endpoint = False)
print(x)

[10. 12. 14. 16. 18.]


In [32]:
#Find retstep value
x = np.linspace(1,2,5, retstep = True)
print(x)

(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)


In [ ]:
#retstep here is 0.25
#(Start-Stop) / (num - 1)