In [1]:
import numpy as np

a = np.arange(10,21,1)
s = slice(2,7,2)
print(a[s])

[12 14 16]


In [2]:
b = a[2:7:2]
print(b)

[12 14 16]


In [3]:
#slice single item
a = np.arange(10)
b = a[5]
print(b)

5


In [4]:
#Slice items starting from index
a = np.arange(10)
print(a[2:])       #after : means it will take the whole values or range

[2 3 4 5 6 7 8 9]


In [5]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [35]:
#Slice items strating from index
print('Now we will slice the array from the index a[1:]')
print(a[1:])
print(a.ndim)


Now we will slice the array from the index a[1:]
[[4 5 6]
 [7 8 9]]
2


In [8]:
print(a[1][2])   #1st row 2nd Columb

6


In [9]:
print(a[1][1:])

[5 6]


In [12]:
#this returns array items in the second column
print('The items in the second column are:')
print(a[..., 1])      #here ... means considering all the rows and 1 is for 1st column
print('\n')

The items in the second column are:
[2 5 8]




In [13]:
#now we will slice all items from the second row
print('The items in the second row are:')
print(a[1, ...])      #here ... means considering all the columns with ist row
print('\n')

The items in the second row are:
[4 5 6]




In [14]:
#now we willslice all items from column 1 onwards
print('The items in the column 1 onwards are:')
print(a[..., 1:])      #here ... means considering all the rows and column 1st and 2nd
print('\n')

The items in the column 1 onwards are:
[[2 3]
 [5 6]
 [8 9]]




In [18]:
print('printing 7 8')
print(a[2][:2])

printing 7 8
[7 8]


In [23]:
print('printing 3 6')
print(a[0][2:])

printing 3 6
[3]


In [28]:
print(a[:2][:2])

[[1 2 3]
 [4 5 6]]


In [38]:
print(a[:2,:1])

[[1]
 [4]]


In [34]:
print(a[..., :2])

[]


#Advance Sclicing

In [4]:
import numpy as np

x = np.array([[1,2], [3,4], [5,6]])
y = x[[0,1,2], [0,1,0]]    #00 -- 11  --20

print(x)
print('------------')
print(y)

[[1 2]
 [3 4]
 [5 6]]
------------
[1 4 5]


In [5]:
x = np.array([[0,1,2], [3,4,5], [6,7,8], [9,10,11]])
print(x)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [8]:
rows = np.array([[0,0], [3,3]])
cols = np.array([[0,2], [0,2]])

y = x[rows, cols]

print(rows)
print('-----------------')
print(cols)

print('The corner elements of this array are:')
print(y)

[[0 0]
 [3 3]]
-----------------
[[0 2]
 [0 2]]
The corner elements of this array are:
[[ 0  2]
 [ 9 11]]


In [9]:
print('Printing 3 1 2 and 6 10 8')
rows = np.array([1,0,1], [2,3,2])
cols = np.array([0,1,2], [0,1,2])

Printing 3 1 2 and 6 10 8


TypeError: data type not understood

In [10]:
import numpy as np

x = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])

print('our array is')
print(x)
print('\n')

our array is
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]




In [11]:
#Sclicing
z = x[1:4, 1:3]

print('After sclicing the arraybecomes')
print(z)
print('\n')

After sclicing the arraybecomes
[[ 4  5]
 [ 7  8]
 [10 11]]




In [12]:
#using Advance INdex for Sclicing
y =x[1:4, [1,2]]
print('Sclicing using Advance index of column:')
print(y)

Sclicing using Advance index of column:
[[ 4  5]
 [ 7  8]
 [10 11]]


In [13]:
x = np.array([0,1,2,3,4,5,6,7,8,9,10,11])

print('our array is:')
print(x)
print('\n')

our array is:
[ 0  1  2  3  4  5  6  7  8  9 10 11]




In [14]:
#Now printing items greater than 5
print('Items Greater than 5:')
print(x[x > 5])

Items Greater than 5:
[ 6  7  8  9 10 11]


In [15]:
#example
a = np.array([np.nan, 1,2,np.nan,3,4,5])
print(a[~np.isnan(a)])

[1. 2. 3. 4. 5.]


In [18]:
#example
a = np.array([1, 2+6j, 5, 3.5+5j])
print(a[np.iscomplex(a)])

[2. +6.j 3.5+5.j]
